#!/usr/bin/env python3
"""Scan the asset folders and write the files the editor and the icon atom need.
Re-run after adding or removing files:  python3 tools/build_assets.py

  tds/assets/index.json              images / graphics / videos manifest (for the editor)
  tds/atoms/icon/glyphs.json         the icon glyph list (for the icon atom's canvas page)
  tds/atoms/icon/icons.css           one .icon-<name> class per glyph (masks)"""
import json, os, re, struct

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ASSETS = os.path.join(ROOT, "tds/assets")
ICON = os.path.join(ROOT, "tds/atoms/icon")
SKIP = {".gitkeep", "placeholder", ".DS_Store"}


def slug(filename):
    base = re.sub(r"^Name=", "", os.path.splitext(filename)[0])
    return re.sub(r"[^a-z0-9]+", "-", base.lower()).strip("-")


def dims(path):
    ext = os.path.splitext(path)[1].lower()
    try:
        if ext == ".png":
            with open(path, "rb") as f:
                return struct.unpack(">II", f.read(24)[16:24])
        if ext == ".svg":
            s = open(path, encoding="utf-8").read(600)
            w, h = re.search(r'width="([\d.]+)', s), re.search(r'height="([\d.]+)', s)
            if w and h:
                return float(w.group(1)), float(h.group(1))
    except Exception:
        pass
    return None, None


def items(folder, base):
    out = []
    for fn in sorted(os.listdir(folder), key=str.lower):
        p = os.path.join(folder, fn)
        if fn in SKIP or not os.path.isfile(p):
            continue
        w, h = dims(p)
        out.append({"name": slug(fn), "file": os.path.relpath(p, base).replace(os.sep, "/"),
                    "width": w, "height": h, "bytes": os.path.getsize(p)})
    return out


def write(path, text):
    with open(path, "w") as f:
        f.write(text)


# ---- assets: images / graphics / videos (a folder may hold files directly and/or subfolders = groups)
libs = []
for lib in ("images", "graphics", "videos"):
    folder = os.path.join(ASSETS, lib)
    groups = []
    direct = items(folder, ASSETS)
    if direct:
        groups.append({"id": "all", "label": "All", "items": direct})
    for sub in sorted(os.listdir(folder)):
        if os.path.isdir(os.path.join(folder, sub)):
            groups.append({"id": sub, "label": sub.replace("-", " ").title(), "items": items(os.path.join(folder, sub), ASSETS)})
    libs.append({"id": lib, "label": lib.title(), "groups": groups})
write(os.path.join(ASSETS, "index.json"), json.dumps({"libraries": libs}, indent=1) + "\n")

# ---- icon glyphs
glyphs = items(os.path.join(ICON, "glyphs"), ICON)
names = [g["name"] for g in glyphs]
assert len(names) == len(set(names)), "duplicate icon names"
write(os.path.join(ICON, "glyphs.json"), json.dumps({"items": glyphs}, indent=1) + "\n")
css = ['/* GENERATED by tools/build_assets.py — one class per glyph. Usage: <i class="icon icon-check"></i> */']
for g in glyphs:
    u = 'url("%s")' % g["file"].replace(" ", "%20").replace("=", "%3D")
    css.append(".icon-%s { -webkit-mask-image: %s; mask-image: %s; }" % (g["name"], u, u))
write(os.path.join(ICON, "icons.css"), "\n".join(css) + "\n")

print("glyphs:", len(glyphs), "| images:", sum(len(g["items"]) for l in libs if l["id"] == "images" for g in l["groups"]))
