#!/usr/bin/env python3
"""Scan tds/libraries and write index.json (for the editor) and icons.css (icon helper).
Re-run after adding or removing assets:  python3 tools/build_libraries.py"""
import json, os, re, struct

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LIB = os.path.join(ROOT, "tds/libraries")
SKIP = {".gitkeep", "placeholder", ".DS_Store", "index.json", "icons.css"}


def slug(filename):
    base = os.path.splitext(filename)[0]
    base = re.sub(r"^Name=", "", base)
    return re.sub(r"[^a-z0-9]+", "-", base.lower()).strip("-")


def dims(path):
    ext = os.path.splitext(path)[1].lower()
    try:
        if ext == ".png":
            with open(path, "rb") as f:
                head = f.read(24)
            return struct.unpack(">II", head[16:24])
        if ext == ".svg":
            s = open(path, encoding="utf-8").read(600)
            w, h = re.search(r'width="([\d.]+)', s), re.search(r'height="([\d.]+)', s)
            if w and h:
                return float(w.group(1)), float(h.group(1))
    except Exception:
        pass
    return None, None


def items(folder):
    out = []
    for fn in sorted(os.listdir(folder), key=str.lower):
        p = os.path.join(folder, fn)
        if fn in SKIP or not os.path.isfile(p):
            continue
        w, h = dims(p)
        out.append({"name": slug(fn), "file": os.path.relpath(p, LIB).replace(os.sep, "/"),
                    "width": w, "height": h, "bytes": os.path.getsize(p)})
    return out


libs = []
for lib in ("icons", "images", "graphics", "videos"):
    folder = os.path.join(LIB, lib)
    groups = []
    direct = items(folder)
    if direct:
        groups.append({"id": "all", "label": "All", "items": direct})
    for sub in sorted(os.listdir(folder)):
        if os.path.isdir(os.path.join(folder, sub)):
            groups.append({"id": sub, "label": sub.replace("-", " ").title(), "items": items(os.path.join(folder, sub))})
    libs.append({"id": lib, "label": lib.title(), "groups": groups})

with open(os.path.join(LIB, "index.json"), "w") as f:
    json.dump({"libraries": libs}, f, indent=1)
    f.write("\n")

icons = next(l for l in libs if l["id"] == "icons")["groups"]
css = ["/* GENERATED by tools/build_libraries.py — one class per icon. Usage: <i class=\"icon icon-check\"></i> */"]
for g in icons:
    for it in g["items"]:
        u = 'url("%s")' % it["file"].replace(" ", "%20").replace("=", "%3D")
        css.append(".icon-%s { -webkit-mask-image: %s; mask-image: %s; }" % (it["name"], u, u))
with open(os.path.join(LIB, "icons.css"), "w") as f:
    f.write("\n".join(css) + "\n")

names = [it["name"] for g in icons for it in g["items"]]
assert len(names) == len(set(names)), "duplicate icon slugs"
print("icons:", len(names), "| images:", sum(len(g["items"]) for g in next(l for l in libs if l["id"] == "images")["groups"]))
